# Generated by Django 4.2.4 on 2023-09-20 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_grupo_creargasto_grupo_ingresaringresos_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
    ]
